### ISSUE TITLE
Add new color themes (html,css only)

### ISSUE THREAD

**Issue by Nainish-Rai** [Nainish-Rai/aesthetic-startpage#1]
Hey Check this repo there are 4 color themes, Make a new color theme for the project.

**Comment by Utkarsh212** [comment]
Please assign it to me so that it could work upon it

**Comment by sumitbaroniya** [comment]
Please assign me this issue. I would like to contribute in it.

**Comment by Nainish-Rai** [comment]
@sumitbaroniya you can start working on it; Just make sure you make a new unique color theme

**Comment by hamzailyas237** [comment]
I want to work on this please assign it ?

**Comment by Hiresh23** [comment]
I would like to work on this issue , i am a painter also so i feel i could be of good help
please assign
