### ISSUE TITLE
Add a new gradient -colour theme

### ISSUE THREAD

**Issue by Morbius00** [Nainish-Rai/aesthetic-startpage#10]
![Open Source Love](https://badges.frapsoft.com/os/v1/open-source.svg?v=103)

## Gradient colour
getting bored  from normal colour why not add a spice of colour gradient using 
<a href="https://www.w3schools.com/css/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg" alt="css3" width="40" height="40"/>   <a href="https://www.w3.org/html/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg" alt="html5" width="40" height="40"/> </a>

**Comment by Nainish-Rai** [comment]
@Morbius00 Sounds cool! You wanna try?

**Comment by vinayjain18** [comment]
Can you assign this to me @Nainish-Rai ?

**Comment by Nainish-Rai** [comment]
@vinayjain18 Assigned; You can start working on it.

**Comment by Morbius00** [comment]
> @Morbius00 Sounds cool! You wanna try?

I gave you the idea then definitely i am going to do it..but you assigned it to vinayjain18 why?

**Comment by Nainish-Rai** [comment]
@Morbius00 I have assigned you new issue which u raised.

**Comment by Debarpan08** [comment]
@Nainish-Rai Sir, I really want to work on this. Can you assign this to me?
