### ISSUE TITLE
Add new colour with mesh gradient 

### ISSUE THREAD

**Issue by Divya2163** [Nainish-Rai/aesthetic-startpage#13]
Add new mesh gradient theme with glassmorphism. Kindly assign me this with hacktoberfest labels.

**Comment by Nainish-Rai** [comment]
@Divya2163 Added; You can start

**Comment by Nainish-Rai** [comment]
@Divya2163 You PR was great and merged; There was a minor bug which was fixed; Should I close this issue or You want to make more themes?

**Comment by Divya2163** [comment]
I want to make more themes with different colour gradients.
