### ISSUE TITLE
feat: Making Changes in UI

### ISSUE THREAD

**Issue by superiorsd10** [Nainish-Rai/aesthetic-startpage#17]
Hey! I want to make some changes to the UI by using the library `particles.js`. That'll be looking too cool, and UI will look good.
Please assign this issue to me.

**Comment by Nainish-Rai** [comment]
@superiorsd10 Go ahead. Excited to see new UI

**Comment by superiorsd10** [comment]
@Nainish-Rai Do I have to make changes in all the folders?

**Comment by Nainish-Rai** [comment]
@superiorsd10 No; just make a separate folder for your ui/theme. Make one theme then we will mutually decide to implement it to all.

**Comment by superiorsd10** [comment]
I'm sharing a demonstration of how it's gonna look, please check it, and tell me if I'll have to apply it to all the folders.
@Nainish-Rai Actually I didn't mean to create a new theme, I wanted to modify the existing ones.

https://user-images.githubusercontent.com/92971894/193897764-11b0aaca-3102-4009-b11d-e89213b005cf.mp4

**Comment by superiorsd10** [comment]
@Nainish-Rai Sorry for the bad video quality, I'd compress the original screen recording, that's why those white spots are visible there, but it's not visible in real.

**Comment by Nainish-Rai** [comment]
@superiorsd10 Okay so make a copy of this theme and make a new folder for your ui ; Name the folder as particle-white ;Also can you slow down the animation speed?

**Comment by superiorsd10** [comment]
@Nainish-Rai Okay I'll be doing that! Also, do I have to make a copy of all the themes?

**Comment by Nainish-Rai** [comment]
@superiorsd10 No only this theme you used in video; since background particles are white.

**Comment by superiorsd10** [comment]
@Nainish-Rai I can change the color of the particles according to the theme if you say.

**Comment by Nainish-Rai** [comment]
@superiorsd10 First let try with one theme. Then we will decide

**Comment by superiorsd10** [comment]
@Nainish-Rai Okay! I've made a PR. So please review it.
