### ISSUE TITLE
New Color Schemes (Nordic / Retrowave /Synthwave /Aesthetic / Etc) CSS only 

### ISSUE THREAD

**Issue by Nainish-Rai** [Nainish-Rai/aesthetic-startpage#20]
Add a new color scheme for the startpage

**Comment by Sidd2024** [comment]
hello, @Nainish-Rai I would love to work on this issue!❤️, please assign it to me.
also can you share some resources and SS of color schemes you are talking about?😅

**Comment by deepesh16b** [comment]
I know CSS, I can do this. Please assign this to me

**Comment by Nainish-Rai** [comment]
@Sidd2024 you can find color scheme ideas on pinterest and images/gifs too

**Comment by Nainish-Rai** [comment]
@deepesh16b you can also work on it

**Comment by Sidd2024** [comment]
@deepesh16b thanks for the help.👍🏻
I also wanted to tell you that your repo doesn't have a contributing.md file, necessary for projects participating in hacktobefest.

**Comment by Nainish-Rai** [comment]
@Sidd2024 It is in progress issue #18 and PR is being counted in hacktoberfest

**Comment by Sidd2024** [comment]
hey @Nainish-Rai just raised PR #38 for synthwave color scheme. should I add others as well, like this?

**Comment by Nainish-Rai** [comment]
@Sidd2024 Your PR is merged, You did great ; You can add more themes like this if you want,just follow the template given

**Comment by Hiresh23** [comment]
i would like to contribute to this issue

**Comment by Nainish-Rai** [comment]
@Hiresh23 I have assigned you, You can start working; Also make sure to read guide at end of readme
