### ISSUE TITLE
animated colour gradient

### ISSUE THREAD

**Issue by Morbius00** [Nainish-Rai/aesthetic-startpage#29]
![Open Source Love](https://badges.frapsoft.com/os/v1/open-source.svg?v=103)

## Gradient colour
getting bored  from normal colours and colour mest why not add a spice of animation colour gradient using 
<a href="https://www.w3schools.com/css/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg" alt="css3" width="40" height="40"/>   <a href="https://www.w3.org/html/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg" alt="html5" width="40" height="40"/> </a>

**Comment by Nainish-Rai** [comment]
@Morbius00 Sounds Cool!

**Comment by Nainish-Rai** [comment]
@Morbius00 I have assigned you, You can start working on it.
