### ISSUE TITLE
Make a dropdown menu on top right to change theme (CSS)

### ISSUE THREAD

**Issue by Nainish-Rai** [Nainish-Rai/aesthetic-startpage#39]
Make a minimal menu on top-right to change themes (Javascript code is available in theme-switch branch)

**Comment by yes-im-harsh** [comment]
I would like to contribute

**Comment by Nainish-Rai** [comment]
@yes-im-harsh I have assigned you. You can get theme-change code in theme-switch branch index.html;
You should create a menu on right with theme list

**Comment by yes-im-harsh** [comment]
You already have the option to change the theme 
![image](https://user-images.githubusercontent.com/76259017/194108321-97ec4205-7b91-4cad-8a04-d4cf5097f1bb.png)
 Do you want me to remove it, and create a dropdown on the top right?

**Comment by Nainish-Rai** [comment]
@yes-im-harsh Yes remove it, you can use its code , Make theme list of Main-themes folder , Use name(color) as theme indicator instead of buttons

**Comment by Nainish-Rai** [comment]
@yes-im-harsh Make a small button at top right which bring theme list from right. list should be hidden by default and visible when button is clicked

**Comment by Nainish-Rai** [comment]
@yes-im-harsh Yes

**Comment by Nainish-Rai** [comment]
@yes-im-harsh Code it in such a way that it will be easier to add new themes to it

**Comment by yes-im-harsh** [comment]
Take a look
![one](https://user-images.githubusercontent.com/76259017/194132076-34e717bc-f371-4152-aab1-768219528e48.jpg)
![two](https://user-images.githubusercontent.com/76259017/194132113-4334f0f0-7811-469a-b13b-e9520d15a5ae.jpg)

**Comment by Nainish-Rai** [comment]
@yes-im-harsh This looks great, Add some space from right for longer names; Also reduce the size of button a little.

**Comment by yes-im-harsh** [comment]
I have implemented the Hamburger menu and the theme is also changing, but how do you want your folder structure to be, Right now I have done all the work inside main-theme/blue (index.html and style.css). You want me to copy & paste the same code inside the html and css of all the themes inside main theme? Or How?

**Comment by yes-im-harsh** [comment]
@Nainish-Rai , I request you to take a look PR: #51 and merge it
I will help me in Hacktoberfest contribution. @Nainish-Rai

**Comment by Nainish-Rai** [comment]
@yes-im-harsh I have check your PR menu is working fine. Just put the new index.html in parent folder of repo and use the old index.html in theme folder(given in template folder). CSS is fine just don't comment .html{flex property}

**Comment by yes-im-harsh** [comment]
> @yes-im-harsh I have updated hamburger style check it and use it for all main-themes and also don't comment out html flex

I have created an index.html folder in the root and theme(main-themes) is changing.
But If I use the html flex, then I have to use the flex-wrap.

With flex in html
![image](https://user-images.githubusercontent.com/76259017/194484732-af36591e-aa8b-46dd-8fa9-1459565b95ae.png)

Without flex
![image](https://user-images.githubusercontent.com/76259017/194484871-386dab2a-b6d6-4a6a-abfd-67ac2cf8ac1e.png)

Do you still want me to uncomment flex from html? @Nainish-Rai

**Comment by yes-im-harsh** [comment]
Please check PR: #51. I have done all the changes.

**Comment by Nainish-Rai** [comment]
@yes-im-harsh Your PR is merged, Thanks for contributing.

**Comment by yes-im-harsh** [comment]
Thanks for the coordination and support, looking forward to more contributions😀
