### ISSUE TITLE
Make a guide to add new themes using template

### ISSUE THREAD

**Issue by Nainish-Rai** [Nainish-Rai/aesthetic-startpage#45]
Make a guide to make new theme using the template given. Add that at he end of readme

**Comment by getmeapencil** [comment]
You can assign it to me.

**Comment by Nainish-Rai** [comment]
@getmeapencil Sure assigned

**Comment by Nainish-Rai** [comment]
@getmeapencil Your PR is merged, Thanks for contributing. You are always free to open issues for improvement and suggestions
