### ISSUE TITLE
hacker theme

### ISSUE THREAD

**Issue by piyushkdas0611** [Nainish-Rai/aesthetic-startpage#48]
I would like to contribute a hacker theme in the new themes

**Comment by Nainish-Rai** [comment]
@piyushkdas0611 You can make themes but it should follow the template

**Comment by piyushkdas0611** [comment]
![hackerstartpage](https://user-images.githubusercontent.com/96428820/196194508-6b11381c-681d-479f-91d9-9b074bfe8d50.png)

How is this? Give a review.
