### ISSUE TITLE
add new color theme (css only)

### ISSUE THREAD

**Issue by Nainish-Rai** [Nainish-Rai/aesthetic-startpage#5]
Add a new color theme for the startpage

**Comment by heisdinesh** [comment]
can i work on this issue @Nainish-Rai

**Comment by Nainish-Rai** [comment]
Sure @heisdinesh , You can start working on it.

**Comment by shidoitsuka** [comment]
hi, can you check on #6 thanks

**Comment by sumitbaroniya** [comment]
Please assign me this issue. I would like to contribute in it.

**Comment by Nainish-Rai** [comment]
@oooo-ankit yes you can start working on it
