### ISSUE TITLE
Wants to add icons for better UX.

### ISSUE THREAD

**Issue by DeveloperAshish8** [Nainish-Rai/aesthetic-startpage#52]
### **Before**
![Screenshot (4)](https://user-images.githubusercontent.com/90233808/194481618-dcbb73d0-8b38-489a-a914-0564e41bf5d4.png)

### **After**
![Screenshot (3)](https://user-images.githubusercontent.com/90233808/194481691-05dd095b-0fec-4600-867b-2b1ca573850a.png)

Please assign me this task as a hacktoberfest participant.

**Comment by Nainish-Rai** [comment]
@DeveloperAshish8 This looks nice, But this is a minimal design and we prefer text only.

**Comment by DeveloperAshish8** [comment]
But but this can be done by bootstrap icons in just 1 line of codes.

**Comment by Nainish-Rai** [comment]
@DeveloperAshish8 Yeah, But theme is minimal so it's better to not use icons

**Comment by koushikpaul-06** [comment]
Hi, I can contribute to it. Please assign this to me and I will surely give my best to deliver the output you're looking for.

**Comment by Nainish-Rai** [comment]
@DeveloperAshish8 @koushikpaul-06 you can check issue #20  and add more themes
