### ISSUE TITLE
New Themes

### ISSUE THREAD

**Issue by Nainish-Rai** [Nainish-Rai/aesthetic-startpage#65]

**Comment by Nainish-Rai** [comment]
@anayatkhan1 You just have to make a new unique color theme; You can check guide at readme end

**Comment by itsBaivab** [comment]
Can you assign this to me? I can add some new ones

**Comment by Nainish-Rai** [comment]
@itsBaivab Assigned; You can start working on it.

**Comment by Anand-shreya** [comment]
can you assign this to me also, I want to contribute

**Comment by anayatkhan1** [comment]
> can you assign this to me also, I want to contribute

You can start contributing.

**Comment by Anand-shreya** [comment]
> 

I made one PR please have a look at it.

**Comment by dis-28** [comment]
can i please work on it?

**Comment by Rajeshwari-Jadhav** [comment]
I've made a PR. Please check it out.
