### ISSUE TITLE
Better UX

### ISSUE THREAD

**Issue by ABHISHEK-565** [Nainish-Rai/aesthetic-startpage#72]
![image](https://user-images.githubusercontent.com/80988197/195992985-766a62ff-5792-427f-a752-22406373a0d9.png)
You should prefer the icons instead of names, it will give aesthetic and standard look to the website. On hovering the name of the icon should be displayed in subscript.

**Comment by Nainish-Rai** [comment]
@ABHISHEK-565 I think that will not look good with the theme combination
