### ISSUE TITLE
create a button to change themes (html css javascript)

### ISSUE THREAD

**Issue by Nainish-Rai** [Nainish-Rai/aesthetic-startpage#8]
There are many themes of the page in repo.
You have to create a button to change color theme and img using javascript

**Comment by Aryangp** [comment]
Hi want to work on this issue pls assign this issue to me

**Comment by Nainish-Rai** [comment]
@Aryangp You can start working on it

**Comment by Nainish-Rai** [comment]
@Aryangp you can put all img/gif in one main folder and use color in css as variables to make things easier

**Comment by Aryangp** [comment]
i was thinking is using a single html file and putting all css file in one folder and images in one folder .changing css link with the help of  javascript what do you think

**Comment by Nainish-Rai** [comment]
@Aryangp Okay, This idea looks good. Just remember to to rename img/gif acc to theme name ex-blue.gif and same with css.So it will be easier to add new themes

**Comment by Aryangp** [comment]
ok i will remember

**Comment by Nainish-Rai** [comment]
@Aryangp Your PR has been merged, I have created a new issue continuing this #39   You can check if you want

**Comment by Aryangp** [comment]
Ok I will
