### ISSUE TITLE
MacOS Safari

### ISSUE THREAD

**Issue by meksrc** [Nainish-Rai/aesthetic-startpage#87]
Hey Guys,

just so you know, I bet its not at the top of the to do list, but on Safari the page is broken.
I am pretty new to css etc. but if I have the time maybe I will try to fix it.

Nice page btw!

**Comment by Nainish-Rai** [comment]
@meksrc  Hello, I made this page when was a beginner. So, didn't payed attention to compatibility.
It's will be useful if you add safari support, Thank you
