### ISSUE TITLE
Fix size issues on new devices

### ISSUE THREAD

**Issue by Nainish-Rai** [Nainish-Rai/aesthetic-startpage#88]
Make it look like 80% zoom by default

**Comment by archziac** [comment]
> Make it look like 80% zoom by default

Hey how do i make it look like 80% zoom?

**Comment by Nainish-Rai** [comment]
By 80% zoom I mean do ctrl+(-) to get 80% zoom and check the layout . now change css to get that layout

**Comment by natTar235** [comment]
@Nainish-Rai I would like to solve this problem. Is it still available?

**Comment by Nainish-Rai** [comment]
@natTar235 yeah, you can solve

**Comment by natTar235** [comment]
Can you assigne me please?

I want to clarify what you meant. Now the page looks like this at 100% size:

![1web](https://github.com/Nainish-Rai/aesthetic-startpage/assets/146531455/e35d13e8-5c8a-4065-a6be-39ed30910657)

And you want all pages to be set to 80% size by default so it looks like this? This means that I should change all CSS files.

![2web](https://github.com/Nainish-Rai/aesthetic-startpage/assets/146531455/1b2b7340-9d47-4f9a-bde8-90051ace25a5)

Is it as I described?

**Comment by Nainish-Rai** [comment]
@natTar235 I have assigned you. Yes, I want exactly what you have described above, also remeber to update template css files too
