### ISSUE TITLE
Add new color theme (html css)

### ISSUE THREAD

**Issue by Nainish-Rai** [Nainish-Rai/aesthetic-startpage#9]
Add new color theme to startpage

**Comment by Abhishek3223** [comment]
hey @Nainish-Rai  i would like to do this work

**Comment by Nainish-Rai** [comment]
@Abhishek3223 you can start working on it.

**Comment by sumitbaroniya** [comment]
Please assign me this issue. I would like to contribute in it.

**Comment by Aman0786-git** [comment]
Can you please assign this to me will love to contribute

**Comment by Nainish-Rai** [comment]
@Aman0786-git you can start working; Just make sure you create a new unique color theme

**Comment by Aman0786-git** [comment]
> @Aman0786-git you can start working; Just make sure you create a new unique color theme
Thankyou

**Comment by Nainish-Rai** [comment]
@dheeraj-singh-github You can start working on it.

**Comment by VladenCode** [comment]
Hy. Can I work also on this issue?:)

**Comment by Nainish-Rai** [comment]
Yes, You can start working on it

**Comment by VladenCode** [comment]
Sorry, I am new to open source and a bit confused now. I can see three directories for themes. In which should I create my own theme folder? 
Thank you for your answer. :)

**Comment by Nainish-Rai** [comment]
You can check template-theme/normal to get template theme , open it with
vscode and edit css colors and a img matching theme

**Comment by Nainish-Rai** [comment]
There is a guide at the end of readme

**Comment by VladenCode** [comment]
Yes, thank you! I found it after asking my question, that's why a deleted it. :D Thank you again! Wish you a great day!

**Comment by Gautam2305** [comment]
hey @Nainish-Rai , i want to work on this issue and create a new theme

**Comment by Nainish-Rai** [comment]
@Gautam2305 You can start working on it; Assigned

**Comment by Hiresh23** [comment]
can i work on this issue really would like to help

**Comment by itsBaivab** [comment]
Please assign this to me.
